# projects.tf
# This file was generated by Google Cloud's organization setup checklist

# production environment project
module "dpgraham-com-prod" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 14.2"

  name                 = "dpgraham-prod"
  project_id           = "dpgraham-com-prod"
  org_id               = var.org_id
  folder_id            = module.envs.ids["Production"]
  svpc_host_project_id = module.dpgraham-vpc-host-prod.project_id
  shared_vpc_subnets   = [
    google_compute_subnetwork.subnet_prod_east1.id,
    google_compute_subnetwork.subnet_prod_central1.id
  ]

  billing_account = var.billing_account
}

# development environment project
module "dpgraham-com-dev" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 14.2"

  name                 = "dpgraham-dev"
  project_id           = "dpgraham-com-dev"
  org_id               = var.org_id
  folder_id            = module.envs.ids["Development"]
  svpc_host_project_id = module.dpgraham-vpc-host-nonprod.project_id
  shared_vpc_subnets   = [
    google_compute_subnetwork.subnet_dev_east1.id,
    google_compute_subnetwork.subnet_dev_central1.id
  ]

  billing_account = var.billing_account
}

# host project for a shared VPC for production environments
module "dpgraham-vpc-host-prod" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 14.2"

  name       = "vpc-host-prod"
  project_id = "dpgraham-vpc-host-prod"
  org_id     = var.org_id
  folder_id  = module.common.id

  billing_account                = var.billing_account
  enable_shared_vpc_host_project = true
}

# host project for a shared VPC for non-production environments (dev, staging, etc.)
module "dpgraham-vpc-host-nonprod" {
  source  = "terraform-google-modules/project-factory/google"
  version = "~> 14.2"

  name       = "vpc-host-nonprod"
  project_id = "dpgraham-vpc-host-nonprod"
  org_id     = var.org_id
  folder_id  = module.common.id

  billing_account                = var.billing_account
  enable_shared_vpc_host_project = true
}

#module "dpgraham-logging" {
#  source  = "terraform-google-modules/project-factory/google"
#  version = "~> 14.2"
#
#  name       = "logging"
#  project_id = "dpgraham-logging"
#  org_id     = var.org_id
#  folder_id  = module.common.id
#
#  billing_account = var.billing_account
#}
#
#module "monitoring-prod-km289-xm965" {
#  source  = "terraform-google-modules/project-factory/google"
#  version = "~> 14.2"
#
#  name       = "monitoring-prod"
#  project_id = "monitoring-prod-km289-xm965"
#  org_id     = var.org_id
#  folder_id  = module.common.id
#
#  billing_account = var.billing_account
#}
#
#module "monitoring-nonprod-km289-xm965" {
#  source  = "terraform-google-modules/project-factory/google"
#  version = "~> 14.2"
#
#  name       = "monitoring-nonprod"
#  project_id = "monitoring-nonprod-km289-xm965"
#  org_id     = var.org_id
#  folder_id  = module.common.id
#
#  billing_account = var.billing_account
#}
#
#module "monitoring-dev-km289-xm965" {
#  source  = "terraform-google-modules/project-factory/google"
#  version = "~> 14.2"
#
#  name       = "monitoring-dev"
#  project_id = "monitoring-dev-km289-xm965"
#  org_id     = var.org_id
#  folder_id  = module.common.id
#
#  billing_account = var.billing_account
#}
