version: 2
updates:
  - package-ecosystem: terraform
    directory: /dev
    schedule:
      interval: monthly
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    reviewers:
      - "dpgraham4401"
  - package-ecosystem: terraform
    directory: /prod
    schedule:
      interval: monthly
    labels:
      - "dependencies"
    open-pull-requests-limit: 4
    reviewers:
      - "dpgraham4401"
